import { useRef, useState } from 'react'
import { ArrowsPointingOutIcon, ArrowPathIcon, PlayIcon } from '@heroicons/react/24/outline'
import { alignShoeprints } from './api'
import type { MatchingResult } from './types'

function FileBox({ label, file, onFile }: { label: string; file?: File; onFile: (file?: File) => void }) { const ref = useRef<HTMLInputElement>(null); return <div className="match-file"><b>{label}</b><input ref={ref} type="file" accept="image/jpeg,image/png,image/tiff,.jpg,.jpeg,.png,.tif,.tiff" onChange={event => onFile(event.target.files?.[0])}/><button className="outline" onClick={() => ref.current?.click()}>Chọn ảnh</button><small>{file ? file.name : 'Chưa chọn ảnh'}</small></div> }
const groups: [string, string[]][] = [['Độ chồng lấp', ['q_overlap_1', 'k_overlap_1', 'q_overlap_2', 'k_overlap_2', 'q_overlap_3', 'k_overlap_3', 'q_overlap_5', 'k_overlap_5', 'q_overlap_10', 'k_overlap_10']], ['Chỉ số Jaccard', ['jaccard_round_0', 'jaccard_round_1', 'jaccard_round_2']], ['Khoảng cách nhỏ nhất', ['mean_distance', 'std_distance', 'p10_distance', 'p25_distance', 'median_distance', 'p75_distance', 'p90_distance']], ['Phân cụm', ['cdm_20', 'cpm_20', 'im_20', 'twrm_20', 'cdm_100', 'cpm_100', 'im_100', 'twrm_100']], ['Tương quan pha', ['peak_value', 'psr']], ['Chỉ số ảnh', ['ncc', 'mse', 'ssim']]]

export function MatchingPage() {
  const [q, setQ] = useState<File>(); const [k, setK] = useState<File>(); const [threshold, setThreshold] = useState(128); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [result, setResult] = useState<MatchingResult>()
  const run = async () => { if (!q || !k) { setError('Hãy chọn cả ảnh dấu vết cần giám định và ảnh dấu vết đối chứng.'); return }; setBusy(true); setError(undefined); try { setResult(await alignShoeprints(q, k, threshold)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Đã có lỗi xảy ra.') } finally { setBusy(false) } }
  const reset = () => { setQ(undefined); setK(undefined); setResult(undefined); setError(undefined); setThreshold(128) }
  return <main className="content matching-page"><div className="preprocess-heading"><div><p className="eyebrow">SO KHỚP DẤU VẾT · GIAI ĐOẠN 2</p><h2>Căn chỉnh và so sánh dấu giày</h2><p>ICP hai chiều, multi-start, chọn kết quả bằng proportion overlap. Chưa có dự đoán Random Forest.</p></div></div><section className="card matching-controls"><FileBox label="Q — Dấu vết cần giám định" file={q} onFile={setQ}/><FileBox label="K — Dấu vết đối chứng" file={k} onFile={setK}/><label>Threshold <input type="number" min="0" max="255" value={threshold} onChange={event => setThreshold(Number(event.target.value))}/></label><button className="outline" onClick={reset}><ArrowPathIcon/> Đặt lại</button><button disabled={busy} onClick={run}><PlayIcon/> {busy ? 'Đang căn chỉnh…' : 'Căn chỉnh dấu giày'}</button></section>{error && <p className="preprocess-error">{error}</p>}
  <section className="matching-images"><ImagePanel title="Ảnh gốc Q" source={result?.artifacts.q_original}/><ImagePanel title="Ảnh gốc K" source={result?.artifacts.k_original}/><ImagePanel title="Lớp phủ căn chỉnh Q + K*" source={result?.artifacts.alignment_overlay}/></section>{result && <><section className="card matching-stats"><h3>Thông số căn chỉnh</h3><div>{[['Góc xoay', `${result.alignment.rotation_angle.toFixed(2)}°`], ['Độ dịch chuyển', `X: ${result.alignment.translation[0].toFixed(2)}, Y: ${result.alignment.translation[1].toFixed(2)}`], ['RMSE', result.alignment.rmse.toFixed(4)], ['Độ chồng lấp (d=3)', `${(result.alignment.proportion_overlap * 100).toFixed(2)}%`], ['Tỷ lệ Downsample', `${result.alignment.selected_downsample_ratio * 100}%`], ['Dịch chuyển khởi tạo', result.alignment.selected_initial_shift], ['Hướng ICP', result.alignment.selected_direction], ['Số vòng lặp ICP', String(result.alignment.iterations)]].map(([label, value]) => <div key={label}><small>{label}</small><b>{value}</b></div>)}</div></section><section className="metric-groups">{groups.map(([name, keys]) => <section className="card" key={name}><h3>{name}</h3>{keys.map(key => <p key={key}><span>{key}</span><b>{(result.similarity[key] ?? 0).toFixed(5)}</b></p>)}</section>)}</section><details className="card feature-vector"><summary><ArrowsPointingOutIcon/> Vector đặc trưng (35)</summary><table><tbody>{Object.entries(result.similarity).map(([name,value]) => <tr key={name}><td>{name}</td><td>{value}</td></tr>)}</tbody></table></details></>}</main>
}
function ImagePanel({ title, source }: { title: string; source?: string }) { return <section className="preprocess-artifact"><h3>{title}</h3>{source ? <img src={source} alt={title}/> : <div className="artifact-placeholder">Chưa có kết quả</div>}</section> }
